//Exerc.1-;

function nome(Hericko){
console.log(Hericko)
return
}
nome('Hericko')


//Exerc.2-;

function soma(a,b){
 let res = (a+b)
console.log(res)
return
}

soma(10,10)



//Exerc.3-;

function multiplicação(c,d){
let res = (c*d)
console.log(res)
return
}

multiplicação(10,10)


//Exerc.3-;

function media (e,f,g,h){
let res = (e+f+g+h)/4;
console.log(res);
return
}

media(10,10,10,10)